import {
  mysqlTable,
  mysqlEnum,
  char,
  timestamp,
  varchar,
  int,
  datetime,
} from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/* =======================================
 * VENDOR USERS
 * ======================================= */

export const VendorUserTable = mysqlTable("vendor_users", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: char("phone_number", { length: 10 }).notNull(),
  aadharNo: char("aadhar_no", { length: 12 }).notNull(),
  address: varchar("address", { length: 255 }).notNull(),
  city: varchar("city", { length: 255 }).notNull(),
  district: varchar("district", { length: 255 }).notNull(),
  state: varchar("state", { length: 255 }).notNull(),
  vendorPinCode: char("vendor_pin_code", { length: 6 }).notNull(),

  ...metadata("VUSE"),
});

/* =======================================
 * VENDOR USER RELATIONS
 * ======================================= */

export const VendorUserRelations = relations(VendorUserTable, ({ many }) => ({
  serviceablePincodes: many(ServiceablePincodesTable),
  acceptedScrapItems: many(ScrapItemsTable),
  acceptedScrapCollectionProcess: many(ScrapCollectionProcessTable),
}));

/* =======================================
 * CUSTOMER USERS
 * ======================================= */

export const CustomerUserTable = mysqlTable("customer_users", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: char("phone_number", { length: 10 }).notNull(),
  address: varchar("address", { length: 255 }).notNull(),
  customerPinCode: char("customer_pin_code", { length: 6 }).notNull(),

  ...metadata("CUSE"),
});

/* =======================================
 * CUSTOMER USER RELATIONS
 * ======================================= */

export const CustomerUserRelations = relations(
  CustomerUserTable,
  ({ many }) => ({
    collectionProcesses: many(ScrapCollectionProcessTable),
  }),
);

/* =======================================
 * SCRAP ITEMS
 * ======================================= */

export const ScrapItemsTable = mysqlTable("scrap_items", {
  id: autogeneratedId(),
  productName: varchar("product_name", { length: 255 }).notNull(),
  vendorPrice: int("vendor_price").notNull(),
  customerPrice: int("customer_price").notNull(),
  priceUnit: priceUnitEnums("price_unit").notNull(),

  ...metadata("SCIT"),
});

/* =======================================
 * SCRAP ITEM RELATIONS
 * ======================================= */

export const ScrapItemsRelations = relations(ScrapItemsTable, ({ many }) => ({
  collectionProcesses: many(ScrapCollectionProcessTable),
  assignedVendors: many(VendorUserTable),
}));

/* =======================================
 * SERVICEABLE PINCODES
 * ======================================= */

export const ServiceablePincodesTable = mysqlTable("serviceable_pincodes", {
  id: autogeneratedId(),
  vendorId: foreignId("vendor_id")
    .notNull()
    .references(() => VendorUserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
  pinCode: char("pin_code", { length: 6 }).notNull(),

  ...metadata("SPIN"),
});

/* =======================================
 * SERVICEABLE PINCODE RELATIONS
 * ======================================= */

export const ServiceablePincodesRelations = relations(
  ServiceablePincodesTable,
  ({ many }) => ({
    vendors: many(VendorUserTable),
  }),
);

/* =======================================
 * SCRAP COLLECTION PROCESS
 * ======================================= */

export const ScrapCollectionProcessTable = mysqlTable(
  "scrap_collection_process",
  {
    id: autogeneratedId(),
    customerId: foreignId("customer_id")
      .notNull()
      .references(() => CustomerUserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    vendorId: foreignId("vendor_id").references(() => VendorUserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    scrapItem: foreignId("scrap_item")
      .notNull()
      .references(() => ScrapItemsTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    floor: char("floor", { length: 255 }).notNull(),
    landmark: varchar("landmark", { length: 255 }).notNull(),
    collectionDateTime: datetime("collection_date_time").notNull(),

    ...metadata("SCLP"),
  },
);

/* =======================================
 * SCRAP COLLECTION PROCESS RELATIONS
 * ======================================= */

export const ScrapCollectionProcessRelations = relations(
  ScrapCollectionProcessTable,
  ({ one }) => ({
    customer: one(CustomerUserTable, {
      fields: [ScrapCollectionProcessTable.customerId],
      references: [CustomerUserTable.id],
    }),
    scrapItem: one(ScrapItemsTable, {
      fields: [ScrapCollectionProcessTable.scrapItem],
      references: [ScrapItemsTable.id],
    }),
    vendor: one(VendorUserTable),
  }),
);
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------

// ==================================================
// Types, Enums & Helpers
// ==================================================

export type TableIdentifierToken = "VUSE" | "CUSE" | "SPIN" | "SCLP" | "SCIT";

export function roleEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "role", ["customer", "vendor"]);
}

export function priceUnitEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "price_unit", ["piece", "kilo"]);
}

export function updatedAt(columnName?: string) {
  return timestamp(columnName ?? "updated_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}

export function createdAt(columnName?: string) {
  return timestamp(columnName ?? "created_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}

export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}

export function tableIdentifierToken(columnName?: string) {
  return mysqlEnum(columnName ?? "table_identifier_token", [
    "SCIT",
    "VUSE",
    "CUSE",
    "SPIN",
    "SCLP",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}

export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}

export function autogeneratedId() {
  return char("id", { length: 9 })
    .primaryKey()
    .notNull()
    .$defaultFn(() =>
      crypto.randomUUID().split("-").join("").toUpperCase().slice(0, 9),
    );
}

export function foreignId(columnName: string) {
  return char(columnName, { length: 9 });
}

const tableMap = {
  SCIT: "ScrapItemsTable",
  VUSE: "VendorUserTable",
  CUSE: "CustomerUserTable",
  SPIN: "ServiceablePincodesTable",
  SCLP: "ScrapCollectionProcessTable",
  VSPC: "ScrapCollectionProcessTable",
} as const;

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
