import {
  mysqlTable,
  mysqlEnum,
  char,
  timestamp,
  varchar,
  int,
  datetime,
  primaryKey,
  uniqueIndex,
} from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/* ============================================================
 * USERS
 * ============================================================ */

/**
 * Vendors who collect scrap from customers.
 */
export const Table__VendorUser = mysqlTable("vendor_user", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: phoneNumberColumn("phone_number"),
  aadhaarNumber: char("aadhaar_number", { length: 12 }).notNull(),
  address: varchar("address", { length: 255 }).notNull(),
  city: varchar("city", { length: 255 }).notNull(),
  district: varchar("district", { length: 255 }).notNull(),
  state: varchar("state", { length: 255 }).notNull(),
  pinCode: pinCodeColumn("pin_code"),

  ...metadata("VUSE"),
});

/**
 * Customers who request scrap collection.
 */
export const Table__CustomerUser = mysqlTable("customer_user", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: phoneNumberColumn(),
  address: varchar("address", { length: 255 }).notNull(),
  pinCode: pinCodeColumn("pin_code"),

  ...metadata("CUSE"),
});

/* ============================================================
 * SCRAP ITEMS
 * ============================================================ */

export const Table__ScrapItem = mysqlTable("scrap_item", {
  id: autogeneratedId(),
  productName: varchar("product_name", { length: 255 }).notNull().unique(),
  vendorPrice: int("vendor_price").notNull(),
  customerPrice: int("customer_price").notNull(),
  priceUnit: priceUnitEnum().notNull(),
  commisionRate: int("commision_rate")
    .notNull()
    .$defaultFn(() => 10),

  ...metadata("SCIT"),
});

/* ============================================================
 * VENDOR <-> SCRAP ITEM
 * ============================================================ */

export const Table__VendorScrapItem = mysqlTable(
  "vendor_scrap_item",
  {
    vendorId: foreignId("vendor_id")
      .notNull()
      .references(() => Table__VendorUser.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    scrapItemId: foreignId("scrap_item_id")
      .notNull()
      .references(() => Table__ScrapItem.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),

    ...metadata("VSCI"),
  },
  (table) => [
    primaryKey({
      columns: [table.vendorId, table.scrapItemId],
    }),
  ],
);

/* ============================================================
 * VENDOR SERVICEABLE PINCODES
 * ============================================================ */

export const Table__ServiceablePincode = mysqlTable(
  "serviceable_pincode",
  {
    vendorId: foreignId("vendor_id")
      .notNull()
      .references(() => Table__VendorUser.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    pinCode: pinCodeColumn("pin_code"),

    ...metadata("SPIN"),
  },
  (table) => [
    primaryKey({
      columns: [table.vendorId, table.pinCode],
    }),
  ],
);

/* ============================================================
 * SCRAP COLLECTION ORDERS
 * ============================================================ */

export const Table__ScrapCollectionProcess = mysqlTable(
  "scrap_collection_process",
  {
    id: autogeneratedId(),
    customerId: foreignId("customer_id")
      .notNull()
      .references(() => Table__CustomerUser.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    vendorId: foreignId("vendor_id").references(() => Table__VendorUser.id, {
      onDelete: "set null",
      onUpdate: "cascade",
    }),
    scrapItemId: foreignId("scrap_item_id")
      .notNull()
      .references(() => Table__ScrapItem.id, {
        onDelete: "restrict",
        onUpdate: "cascade",
      }),
    floor: varchar("floor", { length: 50 }).notNull(),
    landmark: varchar("landmark", { length: 255 }).notNull(),
    collectionDateTime: datetime("collection_date_time").notNull(),
    status: scrapCollectionStatusEnum("scrap_collection_status")
      .notNull()
      .$defaultFn(() => "order-placed"),

    ...metadata("SCLP"),
  },
);

/* ============================================================
 * PAYMENTS
 * ============================================================ */

/**
 * Payment information for a scrap collection order.
 */
export const Table__Payment = mysqlTable(
  "payment",
  {
    id: autogeneratedId(),
    vendorId: foreignId("vendor_id")
      .notNull()
      .references(() => Table__VendorUser.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    scrapOrderId: foreignId("scrap_order_id")
      .notNull()
      .references(() => Table__ScrapCollectionProcess.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    razorpayOrderId: varchar("razorpay_order_id", {
      length: 255,
    }).notNull(),
    razorpayPaymentId: varchar("razorpay_payment_id", {
      length: 255,
    }),
    razorpaySignature: varchar("razorpay_signature", {
      length: 255,
    }),

    ...metadata("PAYM"),
  },
  (table) => [
    uniqueIndex("payment_razorpay_order_id_idx").on(table.razorpayOrderId),
  ],
);

/* ============================================================
 * STATES
 * ============================================================ */

export const Table__State = mysqlTable("state", {
  id: varchar("id", { length: 255 }).notNull().primaryKey(),
  stateName: varchar("state_name", { length: 255 }).notNull().unique(),

  ...metadata("STAT"),
});

/* ============================================================
 * DISTRICTS
 * ============================================================ */

/**
 * District belonging to a state.
 */
export const Table__District = mysqlTable("district", {
  id: varchar("id", { length: 255 }).notNull().primaryKey(),
  districtName: varchar("district_name", { length: 255 }).notNull(),
  associatedState: varchar("associated_state", { length: 255 })
    .notNull()
    .references(() => Table__State.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),

  ...metadata("DIST"),
});

/* ============================================================
 * RELATIONS
 * ============================================================ */

/* ============================================================
 * VENDOR USER RELATIONS
 * ============================================================ */

export const Relations__VendorUser = relations(
  Table__VendorUser,
  ({ many }) => ({
    serviceablePincodes: many(Table__ServiceablePincode),

    acceptedScrapItems: many(Table__VendorScrapItem),

    collectionProcesses: many(Table__ScrapCollectionProcess),

    payments: many(Table__Payment),
  }),
);

/* ============================================================
 * CUSTOMER USER RELATIONS
 * ============================================================ */

export const Relations__CustomerUser = relations(
  Table__CustomerUser,
  ({ many }) => ({
    collectionProcesses: many(Table__ScrapCollectionProcess),
  }),
);

/* ============================================================
 * SCRAP ITEM RELATIONS
 * ============================================================ */

export const Relations__ScrapItems = relations(
  Table__ScrapItem,
  ({ many }) => ({
    collectionProcesses: many(Table__ScrapCollectionProcess),

    assignedVendors: many(Table__VendorScrapItem),
  }),
);

/* ============================================================
 * VENDOR SCRAP ITEM RELATIONS
 * ============================================================ */

export const Relations__VendorScrapItem = relations(
  Table__VendorScrapItem,
  ({ one }) => ({
    vendor: one(Table__VendorUser, {
      fields: [Table__VendorScrapItem.vendorId],
      references: [Table__VendorUser.id],
    }),

    scrapItem: one(Table__ScrapItem, {
      fields: [Table__VendorScrapItem.scrapItemId],
      references: [Table__ScrapItem.id],
    }),
  }),
);

/* ============================================================
 * SERVICEABLE PINCODE RELATIONS
 * ============================================================ */

export const Relations__ServiceablePincodes = relations(
  Table__ServiceablePincode,
  ({ one }) => ({
    vendor: one(Table__VendorUser, {
      fields: [Table__ServiceablePincode.vendorId],
      references: [Table__VendorUser.id],
    }),
  }),
);

/* ============================================================
 * SCRAP COLLECTION PROCESS RELATIONS
 * ============================================================ */

export const Relations__ScrapCollectionProcess = relations(
  Table__ScrapCollectionProcess,
  ({ one, many }) => ({
    customer: one(Table__CustomerUser, {
      fields: [Table__ScrapCollectionProcess.customerId],
      references: [Table__CustomerUser.id],
    }),

    vendor: one(Table__VendorUser, {
      fields: [Table__ScrapCollectionProcess.vendorId],
      references: [Table__VendorUser.id],
    }),

    scrapItem: one(Table__ScrapItem, {
      fields: [Table__ScrapCollectionProcess.scrapItemId],
      references: [Table__ScrapItem.id],
    }),

    payments: many(Table__Payment),
  }),
);

/* ============================================================
 * PAYMENT RELATIONS
 * ============================================================ */

export const Relations__Payment = relations(Table__Payment, ({ one }) => ({
  vendor: one(Table__VendorUser, {
    fields: [Table__Payment.vendorId],
    references: [Table__VendorUser.id],
  }),

  scrapOrder: one(Table__ScrapCollectionProcess, {
    fields: [Table__Payment.scrapOrderId],
    references: [Table__ScrapCollectionProcess.id],
  }),
}));

/* ============================================================
 * STATE RELATIONS
 * ============================================================ */

export const Relations__State = relations(Table__State, ({ many }) => ({
  districts: many(Table__District),
}));

/* ============================================================
 * DISTRICT RELATIONS
 * ============================================================ */

export const Relations__District = relations(Table__District, ({ one }) => ({
  state: one(Table__State, {
    fields: [Table__District.associatedState],
    references: [Table__State.id],
  }),
}));

/* ============================================================
 * TYPES, ENUMS & HELPERS
 *
 * Keep these at the bottom.
 * ============================================================ */

/* ============================================================
 * TABLE IDENTIFIER TOKEN
 * ============================================================ */

export type TableIdentifierToken =
  | "VUSE"
  | "CUSE"
  | "SPIN"
  | "SCLP"
  | "SCIT"
  | "STAT"
  | "DIST"
  | "PAYM"
  | "VSCI";

/* ============================================================
 * SCRAP COLLECTION STATUS
 * ============================================================ */

export function SCRAP_COLLECTION_STATUS() {
  return [
    "order-placed",
    "payment-processing",
    "order-accepted",
    "process-completed",
  ] as const;
}

export function scrapCollectionStatusEnum(
  columnName = "scrap_collection_status",
) {
  return mysqlEnum(columnName, SCRAP_COLLECTION_STATUS());
}

/* ============================================================
 * PRICE UNIT
 * ============================================================ */

export function PRICE_UNIT() {
  return ["piece", "kilo"] as const;
}

export function priceUnitEnum(columnName = "price_unit") {
  return mysqlEnum(columnName, PRICE_UNIT());
}

/* ============================================================
 * CREATED AT
 * ============================================================ */

export function createdAt(columnName = "created_at") {
  return timestamp(columnName, {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}

/* ============================================================
 * UPDATED AT
 * ============================================================ */

export function updatedAt(columnName = "updated_at") {
  return timestamp(columnName, {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}

/* ============================================================
 * METADATA
 * ============================================================ */

export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}

/* ============================================================
 * TABLE IDENTIFIER TOKEN COLUMN
 * ============================================================ */

export function tableIdentifierToken(columnName = "table_identifier_token") {
  return mysqlEnum(columnName, [
    "SCIT",
    "VUSE",
    "CUSE",
    "SPIN",
    "SCLP",
    "STAT",
    "DIST",
    "PAYM",
    "VSCI",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}

export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}

/* ============================================================
 * ID HELPERS
 * ============================================================ */

/**
 * Generates a 9-character uppercase ID.
 *
 * Example:
 *   A81F3C921
 */
export function autogeneratedId() {
  return char("id", {
    length: 9,
  })
    .primaryKey()
    .notNull()
    .$defaultFn(() =>
      crypto.randomUUID().replaceAll("-", "").toUpperCase().slice(0, 9),
    );
}

/**
 * Foreign keys use the exact same format as autogeneratedId().
 */
export function foreignId(columnName: string) {
  return char(columnName, {
    length: 9,
  });
}

/* ============================================================
 * COMMON COLUMN HELPERS
 * ============================================================ */

export function phoneNumberColumn(columnName = "phone_number") {
  return char(columnName, {
    length: 10,
  }).notNull();
}

export function pinCodeColumn(columnName = "pin_code") {
  return char(columnName, {
    length: 6,
  }).notNull();
}

/* ============================================================
 * TABLE MAP
 * ============================================================ */

export const tableMap = {
  CUSE: "customer_user",
  VUSE: "vendor_user",
  SCIT: "scrap_item",
  SPIN: "serviceable_pincode",
  SCLP: "scrap_collection_process",
  STAT: "state",
  DIST: "district",
  VSCI: "vendor_scrap_item",
  PAYM: "payment",
} as const;

/* ============================================================
 * TABLE IDENTIFICATION
 * ============================================================ */

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
