import {
  mysqlTable,
  mysqlEnum,
  char,
  timestamp,
  varchar,
  int,
  datetime,
  primaryKey,
} from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/* =======================================
 * VENDOR USERS
 * ======================================= */

export const VendorUserTable = mysqlTable("vendor_user", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: char("phone_number", { length: 10 }).notNull(),
  aadharNo: char("aadhar_no", { length: 12 }).notNull(),
  address: varchar("address", { length: 255 }).notNull(),
  city: varchar("city", { length: 255 }).notNull(),
  district: varchar("district", { length: 255 }).notNull(),
  state: varchar("state", { length: 255 }).notNull(),
  vendorPinCode: char("vendor_pin_code", { length: 6 }).notNull(),

  ...metadata("VUSE"),
});

/* =======================================
 * VENDOR USER RELATIONS
 * ======================================= */

export const VendorUserRelations = relations(VendorUserTable, ({ many }) => ({
  serviceablePincodes: many(ServiceablePincodeTable),
  acceptedScrapItems: many(ScrapItemTable),
  acceptedScrapCollectionProcess: many(ScrapCollectionProcessTable),
}));

/* =======================================
 * CUSTOMER USERS
 * ======================================= */

export const CustomerUserTable = mysqlTable("customer_user", {
  id: autogeneratedId(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  phoneNumber: char("phone_number", { length: 10 }).notNull(),
  address: varchar("address", { length: 255 }).notNull(),
  customerPinCode: char("customer_pin_code", { length: 6 }).notNull(),

  ...metadata("CUSE"),
});

/* =======================================
 * CUSTOMER USER RELATIONS
 * ======================================= */

export const CustomerUserRelations = relations(
  CustomerUserTable,
  ({ many }) => ({
    collectionProcesses: many(ScrapCollectionProcessTable),
  }),
);

/* =======================================
 * VENDOR SCRAP ITEM
 * ======================================= */

export const VendorScrapItemTable = mysqlTable(
  "vendor_scrap_item",
  {
    scrapItemId: foreignId("scrap_item_id")
      .references(() => ScrapItemTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),
    vendorId: foreignId("vendor_id")
      .references(() => VendorUserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),

    ...metadata("VSCI"),
  },
  (t) => [primaryKey({ columns: [t.scrapItemId, t.vendorId] })],
);

/* =======================================
 * VENDOR SCRAP ITEM RELATIONS
 * ======================================= */

export const VendorScrapItemRelations = relations(
  VendorScrapItemTable,
  ({ one }) => ({
    scrapItem: one(ScrapItemTable, {
      fields: [VendorScrapItemTable.scrapItemId],
      references: [ScrapItemTable.id],
    }),

    vendor: one(VendorUserTable, {
      fields: [VendorScrapItemTable.vendorId],
      references: [VendorUserTable.id],
    }),
  }),
);

/* =======================================
 * SCRAP ITEMS
 * ======================================= */

export const ScrapItemTable = mysqlTable("scrap_item", {
  id: autogeneratedId(),
  productName: varchar("product_name", { length: 255 }).notNull(),
  vendorPrice: int("vendor_price").notNull(),
  customerPrice: int("customer_price").notNull(),
  priceUnit: priceUnitEnums("price_unit").notNull(),

  ...metadata("SCIT"),
});

/* =======================================
 * SCRAP ITEM RELATIONS
 * ======================================= */

export const ScrapItemsRelations = relations(ScrapItemTable, ({ many }) => ({
  collectionProcesses: many(ScrapCollectionProcessTable),
  assignedVendors: many(VendorUserTable),
}));

/* =======================================
 * SERVICEABLE PINCODES
 * ======================================= */

export const ServiceablePincodeTable = mysqlTable(
  "serviceable_pincode",
  {
    vendorId: foreignId("vendor_id")
      .notNull()
      .references(() => VendorUserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    pinCode: char("pin_code", { length: 6 }).notNull(),

    ...metadata("SPIN"),
  },
  (t) => [primaryKey({ columns: [t.pinCode, t.vendorId] })],
);

/* =======================================
 * SERVICEABLE PINCODE RELATIONS
 * ======================================= */

export const ServiceablePincodesRelations = relations(
  ServiceablePincodeTable,
  ({ many }) => ({
    vendors: many(VendorUserTable),
  }),
);

/* =======================================
 * SCRAP COLLECTION PROCESS
 * ======================================= */

export const ScrapCollectionProcessTable = mysqlTable(
  "scrap_collection_process",
  {
    id: autogeneratedId(),
    customerId: foreignId("customer_id")
      .notNull()
      .references(() => CustomerUserTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    vendorId: foreignId("vendor_id").references(() => VendorUserTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    scrapItemId: foreignId("scrap_item")
      .notNull()
      .references(() => ScrapItemTable.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    floor: char("floor", { length: 255 }).notNull(),
    landmark: varchar("landmark", { length: 255 }).notNull(),
    collectionDateTime: datetime("collection_date_time").notNull(),
    scrapCollectionstatus: mysqlEnum("scrap_collection_status", [
      "order-placed",
      "order-accepted",
      "order-recived",
      "payment-completed",
      "process-completed",
    ])
      .notNull()
      .$defaultFn(() => "order-placed"),

    ...metadata("SCLP"),
  },
);

/* =======================================
 * SCRAP COLLECTION PROCESS RELATIONS
 * ======================================= */

export const ScrapCollectionProcessRelations = relations(
  ScrapCollectionProcessTable,
  ({ one }) => ({
    customer: one(CustomerUserTable, {
      fields: [ScrapCollectionProcessTable.customerId],
      references: [CustomerUserTable.id],
    }),
    scrapItem: one(ScrapItemTable, {
      fields: [ScrapCollectionProcessTable.scrapItemId],
      references: [ScrapItemTable.id],
    }),
    vendor: one(VendorUserTable),
  }),
);

/* =======================================
 * DISTRICT PROCESS
 * ======================================= */

export const DistrictTable = mysqlTable("district", {
  id: varchar("id", { length: 255 }).notNull().unique(),
  districtName: varchar("district_name", { length: 255 }).notNull().unique(),
  associatedState: varchar("associated_state", { length: 255 })
    .notNull()
    .references(() => StateTable.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),

  ...metadata("DIST"),
});

/* =======================================
 * DISTRICT RELATIONS
 * ======================================= */

export const DistrictRelations = relations(DistrictTable, ({ one }) => ({
  state: one(StateTable, {
    references: [StateTable.id],
    fields: [DistrictTable.associatedState],
  }),
}));

/* =======================================
 * STATES PROCESS
 * ======================================= */

export const StateTable = mysqlTable("state", {
  id: varchar("id", { length: 255 }).notNull().unique(),
  stateName: varchar("state_name", { length: 255 }).notNull().unique(),

  ...metadata("STAT"),
});

/* =======================================
 * STATES RELATIONS
 * ======================================= */

export const StateRelations = relations(
  ScrapCollectionProcessTable,
  ({ many }) => ({
    districts: many(DistrictTable),
  }),
);

// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------
// --------------------------------------------------

// ==================================================
// Types, Enums & Helpers
// ==================================================

export type TableIdentifierToken =
  | "VUSE"
  | "CUSE"
  | "SPIN"
  | "SCLP"
  | "SCIT"
  | "STAT"
  | "DIST"
  | "VSCI";

export function SCRAP_COLLECTION_STATUS() {
  return [
    "order-placed",
    "order-accepted",
    "order-recived",
    "payment-completed",
    "process-completed",
  ] as const;
}

export function scrapCollectionStatusEnums(columnName?: string) {
  return mysqlEnum(
    columnName ?? "scrap_collection_status",
    SCRAP_COLLECTION_STATUS(),
  );
}

export function PRICE_UNIT() {
  return ["piece", "kilo"] as const;
}

export function priceUnitEnums(columnName?: string) {
  return mysqlEnum(columnName ?? "price_unit", PRICE_UNIT());
}

export function updatedAt(columnName?: string) {
  return timestamp(columnName ?? "updated_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date())
    .notNull();
}

export function createdAt(columnName?: string) {
  return timestamp(columnName ?? "created_at", {
    mode: "date",
    fsp: 6,
  })
    .$defaultFn(() => new Date())
    .notNull();
}

export function metadata(token: TableIdentifierToken) {
  return {
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    tableIdentifierToken: tokenColumn(token),
  };
}

export function tableIdentifierToken(columnName?: string) {
  return mysqlEnum(columnName ?? "table_identifier_token", [
    "SCIT",
    "VUSE",
    "CUSE",
    "SPIN",
    "SCLP",
    "STAT",
    "DIST",
    "VSCI",
  ] as [TableIdentifierToken, ...TableIdentifierToken[]]);
}

export function tokenColumn(token: TableIdentifierToken) {
  return tableIdentifierToken().notNull().default(token);
}

export function autogeneratedId() {
  return char("id", { length: 9 })
    .primaryKey()
    .notNull()
    .$defaultFn(() =>
      crypto.randomUUID().split("-").join("").toUpperCase().slice(0, 9),
    );
}

export function foreignId(columnName: string) {
  return char(columnName, { length: 9 });
}

const tableMap = {
  SCIT: "scrap_item",
  VUSE: "vendor_user",
  CUSE: "customer_user",
  SPIN: "serviceable_pincode",
  SCLP: "scrap_collection_process",
  STAT: "state",
  DIST: "district",
  VSCI: "vendor_scrap_item",
} as const;

export function identifyTable(token: keyof typeof tableMap) {
  return tableMap[token];
}
