name: Deploy React App via FTP

on:
  push:
    branches:
      - main # Change if you use a different branch
    paths-ignore:
      - "**/*.md"
      - ".github/**"

  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --no-interactive --approve-builds

      - name: Build React app
        run: pnpm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: dist/client
          log-level: standard
